spring.datasource.url=jdbc:postgresql://localhost:5432/edu2job_db
spring.datasource.username=postgres
spring.datasource.password=Bruno@180605

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect