spring.datasource.url=postgresql://neondb_owner:npg_KYCWnTesqc65@ep-shiny-mud-amryugrb.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Bruno@180605

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect